### PR TITLE
Hosted Weblate mentioned in README

### PR DESCRIPTION
**Pull request by comradekingu**
Required by https://hosted.weblate.org/guide/simple-chess-clock/android-app/

### CODE REVIEW

**Comment by iNtEgraIR2021** [comment]
@simenheg please consider merging this PR as it's required to keep the weblate integration process going.

**Comment by comradekingu** [comment]
True.
https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github
and possibly adding https://github.com/weblate is all it needs technically I think.

**Comment by simenheg** [comment]
Hey guys, thanks for setting up the Weblate project.

@comradekingu, if you could revert the text changes unrelated to the URL change, I can merge the PR.

**Comment by comradekingu** [comment]
@simenheg That is all you. I requested approval so the project wouldn't get deleted.
Do either just the URL or this, and the above on your end, and I think it is all good.

**Pull request closed without merging**
