### PR TITLE
Update English full_description.txt

### PR DESCRIPTION
**Pull request by Sitavi**
Fixed lines distribution to correct a layout issue on F-Droid

### CODE REVIEW

**Comment by simenheg** [comment]
Thanks @Sitavi. Could it perhaps be put all on one line and let F-Droid just do all the wrapping itself?

**Comment by Sitavi** [comment]
@simenheg I think so. Just went to the line to separate the two sentences and have a more airy layout, but it's possible to put everything in one line :)

**Comment by simenheg** [comment]
> @simenheg I think so. Just went to the line to separate the two sentences and have a more airy layout, but it's possible to put everything in one line :)

OK, I think we put it all on one line then (also for the French version), so we avoid getting "unlucky" wraps on different screen widths.

**Comment by simenheg** [comment]
Fixed by cd3380e0a181439aa8dde109b10f10157329ffab.

**Pull request closed without merging**
